name: Main changed - build, then release and update GH Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      node-version: 16.19.0

  update-storybook-on-ghpages:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3.6.0

      - uses: ./.github/actions/cache-restore
        id: cache-node-modules
        with:
          node-version: 16.19.0

      - name: Build storybook
        run: |
          cd packages/ui
          npm run test-generate-output
          npm run build-storybook -- --quiet --loglevel silent

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: packages/ui/storybook-static # The folder the action should deploy.